USE master
GO
CREATE DATABASE PalletTraceDB
GO
USE PalletTraceDB

CREATE TABLE [PRODUCT](
SerialNo varchar(30),
BacthId int,
ProcessTemperature float,
CONSTRAINT PK_PRODUCT PRIMARY KEY (SerialNo)
)
GO

CREATE TABLE PALLET(
PalletId int,
RfidFront varchar(30),
RfidBack varchar(30)
CONSTRAINT PK_PALLET PRIMARY KEY (PalletId)
)
GO

CREATE TABLE PALLET_PRODUCT(
PalletId int,
SerialNo varchar(30),
Position int
CONSTRAINT PK_PALLETPRODUCT PRIMARY KEY(PalletId,SerialNo),
CONSTRAINT FK_PALLETPRODUCT_PALLET FOREIGN KEY(PalletId) REFERENCES PALLET(PalletId),
CONSTRAINT FK_PALLETPRODUCT_PRODUCT FOREIGN KEY (SerialNo) REFERENCES [PRODUCT](SerialNo)
)
GO

